### ISSUE TITLE
Remove jsonpParameter?

### ISSUE THREAD

**Issue by morganherlocker** [Project-OSRM/node-osrm#103]
jsonpParameter does not appear to do anything. There is one test, but the value passed is 'function', and changing this value causes no noticeable change in the output. 

https://github.com/Project-OSRM/node-osrm/blob/master/test/osrm.test.js#L96

The bindings do appear to pass the value into osrm-backend, but my guess is that it is ignored regardless of the value.

**Comment by TheMarex** [comment]
Correct me if I'm wrong, but does JSONP not only make sense in a browser setting? So I also don't see any reason why it should be exposed in node.

**Comment by morganherlocker** [comment]
@TheMarex Correct, or at least a server setting where the interface is a chunk of text that is meant to be parsed by a client (curl, a unix-y cli pipe, clientside js, etc.). This function always returns an actual in memory object, so jsonp is meaningless.

:+1: it's on the chopping block.
