### ISSUE TITLE
remove status on osrm.nearest & osrm.route result

### ISSUE THREAD

**Issue by morganherlocker** [Project-OSRM/node-osrm#105]
The osrm.nearest & osrm.route `result.status` property is currently `0` if the function passed and `undefined` if it failed. This is not an idiomatic way to express the success or failure of a function in node.js. Typically, if an error is returned, status is assumed to be "failure", so a property that also conveys this is redundant. If we still want status, it might be more intuitive to return `1` on success and `0` on failure, but it might be better to simply not expose it at all.

**Comment by TheMarex** [comment]
This is done in the new API.
