### ISSUE TITLE
route_name from osrm.route does not match server API docs

### ISSUE THREAD

**Issue by morganherlocker** [Project-OSRM/node-osrm#106]
From the Berlin test fixture, osrm.route returns:
```
  "route_name": [
    "",
    ""
  ]
```

Whereas the server suggests the result should be a single string.  

> route_name name of the route ("most prominent street") as string 

This may be a matter of simply joining the route_name array at runtime, but considering the test fixture returned an array of empty strings, I want to verify what is really happening here.

**Comment by TheMarex** [comment]
@morganherlocker good catch the server doc seems to be wrong. Updated.
