### ISSUE TITLE
Add api-documentation for trip plugin

### ISSUE THREAD

**Issue by chaupow** [Project-OSRM/node-osrm#107]
hi @morganherlocker,
i heard that you're maintaining the api-documentation so i didnt just want to push something to the branch :) this is an issue to not forgot to write an api-doc for the trip plugin.

Here's what I already wrote and what might be reusable:

========================

## `osrm.trip`

Calculates a short roundtrip that visits every given coordinates

### Parameters

* `coordinates` **`Array<Array<Number>>`** The point to match as a latitude, longitude array.

### Examples

```js
var osrm = new OSRM('berlin-latest.osrm');
var options = {
    coordinates: [[52.542648,13.393252], [52.543079,13.394780], [52.542107,13.397389]]};
osrm.trip(options, function(err, response) {
    if(err) throw err;
});
```

Returns `TripResult`.

**Comment by morganherlocker** [comment]
This is perfect @chaupow. I'll add this to the source comments.

**Comment by TheMarex** [comment]
TODO: This needs to be picked up again when documentjs based docs get merged.

**Comment by springmeyer** [comment]
Going to close this since our API doc (https://github.com/Project-OSRM/node-osrm/blob/develop/API.md#osrmtrip) has this. Let's discuss documentation.js push at https://github.com/Project-OSRM/node-osrm/issues/149
