### ISSUE TITLE
libuv misusage

### ISSUE THREAD

**Issue by ElvenMonky** [Project-OSRM/node-osrm#109]
As stated by libuv authors, their IO thread pool is not intended for long-running computational tasks, like it seems to be used in node-OSRM project.

See more on this:
https://github.com/joyent/libuv/issues/1578
http://docs.libuv.org/en/latest/threadpool.html

**Comment by TheMarex** [comment]
@springmeyer do you have an opinion here? I see the problem with mixing requests in this queue, though I'm also reluctant to add yet another thread pool.

**Comment by springmeyer** [comment]
@ElvenMonky - I don't agree that we are misusing libuv. Our tasks are not long-running: they take milliseconds/seconds not minutes. The existing libuv threadpool that node creates at startup and can be increased in size with `UV_THREADPOOL_SIZE` works great for our purposes. If your concern is that the ability to do async work for tasks like file io might be waiting when the # of routing requests > UV_THREADPOOL_SIZE then I'd say the solution is not for node-osrm to use a separate pool. Rather just write a separate http server to serve routing requests in a different process than other requests. Basically handle dispatching at a higher level than one node process, but spawning multiple processes. This is in concert with the design of node and the https://nodejs.org/api/cluster.html helps you do this.

**Comment by ElvenMonky** [comment]
Thank you for clarification! My task was a distance table of 200k nodes. I did it by splitting to 40k distance table requests 2k nodes each and parallelizing this requests on all CPU cores. Each 2k distance table query takes several seconds.Of course, UV_THREADPOOL_SIZE worked ok for this purpose. It just seemed to me that maybe some nodejs cluster usage might be implemented in node-osrm level rather then custom implementation.

**Comment by ElvenMonky** [comment]
Well, now I see your point as the right one.

**Comment by springmeyer** [comment]
Thanks for the discussions @ElvenMonky - feel free to post back with more insights or questions if you have them. For now I'll close this issue.
