### ISSUE TITLE
Travis debug builds failing against current `develop`

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/node-osrm#116]
The most recent release build worked just fine.  Switching to `osrm-backend` `develop` causes the two Debug builds to fail:

https://travis-ci.org/Project-OSRM/node-osrm/builds/86682471

Both are failing when we run `mocha`

Errors are different on each, but both are related to dynamic loading of `tbb` when `mocha` starts up:
```
./node_modules/.bin/mocha -R spec
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/travis/build/Project-OSRM/node-osrm/lib/binding/osrm.node, 1): Symbol not found: __ZN3tbb18task_group_context22cancel_group_executionEv
  Referenced from: /Users/travis/build/Project-OSRM/node-osrm/lib/binding/osrm.node
  Expected in: flat namespace
 in /Users/travis/build/Project-OSRM/node-osrm/lib/binding/osrm.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/travis/build/Project-OSRM/node-osrm/lib/osrm.js:6:29)
```

/cc @daniel-j-h 
Do we need https://github.com/Project-OSRM/node-osrm/pull/112 ?

**Comment by daniel-j-h** [comment]
Yes #112 is waiting for the next release, but I can't think of its changes to introduce your issues.

Especially because the fixes for all the node-osrm problems (e.g. gcc 4.8 being broken with lto) happened in osrm-backend and are already merged into develop.

**Comment by springmeyer** [comment]
The problem was that in newer versions of osrm-backend libOSRM now depends on tbb symbols whereas previously it did not. So because of this `osrm.node` needs to link `libtbb` which is done in https://github.com/Project-OSRM/node-osrm/commit/5b25e4246a9121cea2df33032674090d38a1cb42.

**Comment by TheMarex** [comment]
Should be fixed by https://github.com/Project-OSRM/osrm-backend/commit/a8f11981e37b09b4724fbb6ed838d7d4337af2c3

**Comment by springmeyer** [comment]
Closing, yes the latest `develop` branch is linking well in Debug and Release. Debug linker lines for reference on OS X are:

```
./gyp-mac-tool flock ./Debug/linker.lock c++ -bundle -Wl,-bind_at_load -Wl,-search_paths_first -mmacosx-version-min=10.8 -arch x86_64 -L./Debug  -o Debug/osrm.node Debug/obj.target/osrm/src/node_osrm.o -undefined dynamic_lookup -L/Users/dane/projects/node-osrm/mason_packages/.link/lib -losrm -ltbb -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lboost_unit_test_framework -lstxxl -ltbbmalloc
```
