### ISSUE TITLE
Support uTurns route parameter

### ISSUE THREAD

**Issue by zavan** [Project-OSRM/node-osrm#117]
This should support the route uTurn parameter, as described [here](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#query-2).

**Comment by zavan** [comment]
This should be as easy as editing this part of the code:
https://github.com/Project-OSRM/node-osrm/blob/master/src/node_osrm.cpp#L170-L179
And writing a simple test.

Unfortunally, I don't have the setup or the time to try it out and create a pull request right now.

**Comment by springmeyer** [comment]
@TheMarex - is this a reasonable thing to add? If so I'll put it on my list to hit.

**Comment by TheMarex** [comment]
@springmeyer in general yes, but lets hold off until post-5.0-api.

**Comment by springmeyer** [comment]
@TheMarex thanks, :+1:

**Comment by TheMarex** [comment]
This is now the `continue_straight` parameter (inverted).
