### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by pnorman** [Project-OSRM/node-osrm#118]
node-osrm doesn't have a license declared. This is preventing me from reusing code from it.

It would also prevent anyone from packaging it.

**Comment by TheMarex** [comment]
It is declared in the `package.json` https://github.com/Project-OSRM/node-osrm/blob/master/package.json#L35 but I can push a copy of the license if that helps you.

**Comment by TheMarex** [comment]
https://github.com/Project-OSRM/node-osrm/blob/master/LICENCE.TXT there you go.

**Comment by pnorman** [comment]
Thanks. Note: the license requires the license be distributed with the code
