### ISSUE TITLE
Move to cmake-js

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/node-osrm#121]
Currently we use `node-pre-gyp` as build system for the `node` C++ part and CMake for the `osrm-backend` part.

Goals:
- Building OSRM in `node-osrm` should work _exactly_ like our integration builds in `osrm-backend`
- Remove dependencies on additional build systems
- Utilize the `trusty` instance type to remove building dependencies ourselves

Missing pieces:
- [ ] Binary publishing (compatible with `node-pre-gyp`, same S3 structure)
- [x] Remove build system abstraction through mason
- [x] Move to `trusty` travis instance type
- [x] Pull in all dependencies from trusty
- [x] Porting to Nan 2 (will make sure this is atomic)
- [x] Add OSX building (using `brew`)
- [ ] Replace installing OSRM with including it as CMake module (will unlock caching)

Working in this PR:
- https://github.com/Project-OSRM/node-osrm/pull/112

/cc  @yhahn @karenzshea

**Comment by springmeyer** [comment]
The goals of the current system are to:

 - Work as much like node.js core's build system as possible
 - Use pre-compiled binaries for speed in packaging (mason)
 - Use static libraries wherever possible (only exception is libtbb) for portability (we want to avoid the use of trusty specific libraries that will not be consistently present on other linux distros or ubuntu versions).
 - Use node-pre-gyp to deploy portable binaries that need no compilation for installing on osx and linux

You mentioned you were hitting linking errors which was the trigger to port to cmake? Are there any tickets on the specific linking errors? Was it 116 when upgrading to latest osrm-backend? If it was only #116 then https://github.com/Project-OSRM/node-osrm/pull/124 solves this and re-writing the build is overkill.

**Comment by TheMarex** [comment]
After discussion in chat, will pause this work. NAN2 port continues in https://github.com/Project-OSRM/node-osrm/pull/125

**Comment by daniel-j-h** [comment]
@TheMarex can this be closed now that we have https://github.com/Project-OSRM/node-osrm/pull/271?

**Comment by TheMarex** [comment]
Yes closing.
