### ISSUE TITLE
Stay in sync with osrm-backend more easily

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#126]
Problem:
- Currently osrm-backend development moves fast and node-osrm development is infrequent.
- This means that any changes need to keep node-osrm working pile up and have more cost to debug/fix when the time comes to release a new node-osrm version

Goals:
- When osrm-backend changes (`develop` branch) we want to be notified if it breaks node-osrm `develop/master` branch
- This will reduce the cost in keeping node-osrm working since we will have a timely sense of why the break occurred and on what osrm-backend commit.

Potential solutions:

1) Just check node-osrm into osrm-backend fully or as a submodule
- pro: easy to do, could then re-use the osrm-backend build for building node-osrm against
- con: makes osrm-backend travis runs more complex / add dependencies, requires all core developers know about node.js, builds node-osrm in an environment that is not portable/able to be published as binaries (without changes)

2) Trigger rebuilds of node-osrm whenever the osrm-backend `develop` branch succeeds
- pro: keeps clean separation
- con: will require some extra orchestration between repos

It looks like this "orchestration" has been done before and we could try http://eng.rightscale.com/2015/04/27/dependent-builds-in-travis.html.

/cc @TheMarex @daniel-j-h @danpat @mikemorris

**Comment by BergWerkGIS** [comment]
> 2) Trigger rebuilds of node-osrm whenever the osrm-backend develop branch succeeds

How about: 
let travis do an empty commit (with GITSHA of backend build in commit message) to `node-osrm` in `after_success`?
Q: how to securely store Github credentials to be able to push?

**Comment by springmeyer** [comment]
I've been thinking more about the two options above. I feel like option 1 is the ideal route.

Option 2 of tying together travis builds would be brittle and not solve another key problem: locally developers of osrm-backend would benefit from instant feedback if refactoring has broken node-osrm (and not just depending on slow travis runs).

@TheMarex - can you let me know what you think about my thoughts below and provide signoff on bundling node-osrm in osrm-backend?

> pro: easy to do, could then re-use the osrm-backend build for building node-osrm against

This is proven and was dead easy to do and immediately reduced duplicated logic around test data setup. Prototype of pulling node-osrm into osrm-backend in process over at https://github.com/Project-OSRM/osrm-backend/compare/bundle. The things that were trimmed, for reference, are: https://gist.github.com/springmeyer/f958fe3bdde83244af34

Next actions on this are to look into cmake integration so that we could actually compile node-osrm when you do `cmake ../ && make` (This would not be used for published node-osrm builds but rather to ensure build breakages are always obvious).

As far as the CONS previously sketched I'll break them now:

> makes osrm-backend travis runs more complex

Barely. The node-osrm build is very fast and light and the tests run quickly. So this will add minimal time and complexity overhead to the build times.

> add dependencies

Only node.js which is easy to install on travis so this is not an issue.

> requires all core developers know about node.js

My understanding is that we want to consider [having osrm-backend use Node.js/Node-osrm for faster testing](https://github.com/Project-OSRM/osrm-backend/issues/1973) so this is okay and ultimately an advantage.

> builds node-osrm in an environment that is not portable/able to be published as binaries (without changes)

This is actually an advantage. Having node-osrm and osrm-backend tests both run using the same dependencies will help us debug failures quicker and in isolation.

We can then add a script that can be run locally and tested via a travis job that builds both osrm-backend and node-osrm against portable static libraries from mason (or some other source) so that we can:
 
  - Have instant feedback whether those dep versions behave the same
  - Have the ability to publish portable node-osrm binaries easily from an osrm-backend commit.

One gocha is that we don't want to have dozens of travis jobs building node-osrm for lots of node versions. To tame that complexity I propose node-osrm only support the latest Node.js LTS release. So we would have one travis job that builds and packages against node 4x.

/cc @danpat @lbud

**Comment by danpat** [comment]
I'm :+1: on bringing `node-osrm` into the fold, I think it will smooth out a lot of workflow.

**Comment by TheMarex** [comment]
How do you see this turn out in build system complexity? Baking `node-osrm` into `osrm-backend` would not just mean we only depend on node, but also gyp and node-pre-gyp and mason for binary builds.

This goes against convention as any other of our `node-` projects demonstrate:

https://github.com/search?utf8=✓&q=org:mapbox+node&type=Repositories&ref=searchresults

In practice we won't see any big changes in the library interface ob OSRM down the road - actual changes required to the node bindings are seldom. We can make sure we detect breaking changes on our unstable branch with downstream builds.

We can simply do `npm install git@github.com:Project-OSRM/node-osrm.git` to get node into `osrm-backend` to run the tests. (well there should be a `package.json` probably)
- This will insure we don't break node, without any repository bundling
- We still can keep all of our binary builds for releases.
- This will work now without any modifications anywhere

If you branch requires a different `node-osrm` version to build - great just point the `package.json` it at a branch in `node-osrm`.

@danpat making deploying experimental osrm version easier something we can solve on the deployment side. Let's discuss this separately.

**Comment by danpat** [comment]
@TheMarex yes, but it just moves that complexity from `node-osrm` into `osrm-backend`.  The complexity has to exist somewhere.  For day-to-day work, the Node bindings don't need to be built every time, imagine `make backend` vs `make bindings` vs `make all`.  We already have plenty of code in `osrm-backend` that's not on the default build path (e.g. `make tests`) and doesn't change often.

The convention exists inside Mapbox when:
   1. the core library iterates distinctly separately to the bindings (e.g. Mapnik 3.0.5 vs node-mapnik 3.4.2)
   2. the library being wrapped is third party (node-eio, node-fontnik)

Neither of these situations apply to OSRM.  If we're going to continue towards the path where we deprecate `osrm-routed` and offer an `expressjs` interface via bindings instead, then `node-osrm` is going to become the embodiment of OSRM, because that's how most users will interact with it.

**Comment by springmeyer** [comment]
> Neither of these situations apply to OSRM.

Correct - osrm is more similiar to mbgl. mbgl puts node bindings inside so they can iterate and get released together.

**Comment by springmeyer** [comment]
>  Baking node-osrm into osrm-backend would not just mean we only depend on node, but also gyp and node-pre-gyp and mason for binary builds.

These dependencies are only a requirement for `node-osrm`, and as long as `node-osrm` is an optional target for an osrm-backend developer then they add no complexity or weight.

If/when OSRM integration tests depend on node-osrm then there is no choice to have that dependence whether or not node-osrm is bundled.

**Comment by TheMarex** [comment]
>  For day-to-day work, the Node bindings don't need to be built every time, imagine make backend vs make bindings vs make all. We already have plenty of code in osrm-backend that's not on the default build path (e.g. make tests) and doesn't change often.

No we need to rebuild every time since we link statically.

> If/when OSRM integration tests depend on node-osrm then there is no choice to have that dependence whether or not node-osrm is bundled.

For me having a completely independent build system draw the concrete line between what should be separated on a by-repository basis. There is a difference between something that is installed as a dependency and something that is baked into the repository and build system structure.

We can continue to have a weak coupling and have something that works _now_ or go down a rabbit hole of redoing the node-osrm build system. Dependencies on `gyp` and `pre-gyp` are a clear no-go for everything that gets merged into `osrm-backend`. Our requirement for supporting binary builds and the fact that `pre-gyp` depends on `gyp` does not make this an easy switch.

Having `node-osrm` merged into `osrm-backend` is also completly independed from whether we have tests that use `node-osrm` or not - since we can easily install it anyway as dependency.

**Comment by springmeyer** [comment]
In the theme of keeping iterating on things as separate my next action has been to make it easier and more clear how to build against a custom osrm-backend version - that is landing over in #160.

Once that and other tasks are settled I'll return here to think through things more. One potential route could be to try bringing node-osrm into osrm-backend and building it using the main osrm-backend/CMakelists.txt. Only when we want to publish a binary would we need to invoke gyp. That way normal C++ development of osrm-backend would be able to ensure node-osrm compiles without having new dependencies (except node). But we could maintain the proven/blessed gyp system that node uses for publishing binaries. Not sure if this is a sound idea - but I'll test it when I have time.

**Comment by daniel-j-h** [comment]
Merged into backend.
