### ISSUE TITLE
How to set options.distance_table now?

### ISSUE THREAD

**Issue by mapolonio** [Project-OSRM/node-osrm#132]
Hello, I see that the API has changed since the last time I built the project and now I have problems with:
```javascript
new OSRM({path: 'some_path', distance_table: 'some_number'})
```

the distance_table parameter is not supported anymore. So, how or where do I set it?

Thanks in advance

**Comment by TheMarex** [comment]
You don't have to. It is not restricted by default.

**Comment by mapolonio** [comment]
Great!
