### ISSUE TITLE
node osrm setup failure

### ISSUE THREAD

**Issue by payanacloud** [Project-OSRM/node-osrm#137]
I have installed node osrm using npm install osrm on Ubuntu 14.04. This has installed the OSRM v4.9. The next step is to setup OSRM. I am trying to follow the steps given in the wiki for setup- https://github.com/Project-OSRM/node-osrm

When I run make I get the below errors

/bin/sh: 1: [[: not found
/bin/sh: 1: echo you need pkg-config installed: not found
make: *** [pkgconfig] Error 127
When I run ./Makefile, I get the below errors

./Makefile: line 3: shell: command not found
./Makefile: line 3: TOOL_ROOT?=/lib/binding: No such file or directory
./Makefile: line 4: TOOL_ROOT: command not found
I even added a shebang to use bash since the errors seem to be due to non usage of bash

I have installed all the required libraries and have node v0.12

How can I run the https://github.com/Project-OSRM/node-osrm/blob/develop/Makefile file successfully?

**Comment by payanacloud** [comment]
I was able to go ahead by adding 
SHELL := /bin/bash

But now I am getting a clang++ error -
''' 
CMake Error at CMakeLists.txt:9 (project):
  The CMAKE_CXX_COMPILER:

    clang++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
'''

Also the CMakeError.log showed the below error-

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: clang++ 
Build flags: 
Id flags: 

The output was:
No such file or directory


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: clang++ 
Build flags: 
Id flags: -c

The output was:
No such file or directory


Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":

**Comment by payanacloud** [comment]
Solved the above by changing bootstrap.sh to use g++ instead of clang++

But get a new error
-- Found LuaJIT: /usr/local/lib/libluajit-5.1.so
-- Performing Test LUABIND51_WORKS
-- Performing Test LUABIND51_WORKS - Failed
CMake Error at cmake/check_luabind.cmake:38 (message):
  Luabind does not work with Lua 5.1 at
  /usr/lib/x86_64-linux-gnu/liblua5.1.so, no working Luabind found
Call Stack (most recent call first):
  CMakeLists.txt:293 (include)


-- Configuring incomplete, errors occurred!
See also "/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/deps/osrm-backend-Release/build/CMakeFiles/CMakeOutput.log".
See also "/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/deps/osrm-backend-Release/build/CMakeFiles/CMakeError.log".
make[1]: Entering directory `/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/deps/osrm-backend-Release/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/deps/osrm-backend-Release/build'
~/truckeasy/projectx-mirror/node_modules/osrm
cp: cannot stat ‘/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/mason_packages/.link/bin/osrm-extract’: No such file or directory
cp: cannot stat ‘/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/mason_packages/.link/bin/osrm-datastore’: No such file or directory
cp: cannot stat ‘/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/mason_packages/.link/bin/osrm-prepare’: No such file or directory
success: now run 'npm install --build-from-source'
gyp: Call to 'pkg-config libosrm --variable=libdir' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--loglevel=error" "--clang=1" "--module=/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/lib/binding/osrm.node" "--module_name=osrm" "--module_path=/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/lib/binding"
gyp ERR! cwd /home/aachar/truckeasy/projectx-mirror/node_modules/osrm
gyp ERR! node -v v0.10.41
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! configure error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --loglevel=error --clang=1 --module=/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/lib/binding/osrm.node --module_name=osrm --module_path=/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.13.0-74-generic
node-pre-gyp ERR! command "node" "/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/node_modules/.bin/node-pre-gyp" "configure" "build" "--loglevel=error" "--clang=1"
node-pre-gyp ERR! cwd /home/aachar/truckeasy/projectx-mirror/node_modules/osrm
node-pre-gyp ERR! node -v v0.10.41
node-pre-gyp ERR! node-pre-gyp -v v0.6.18
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --loglevel=error --clang=1 --module=/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/lib/binding/osrm.node --module_name=osrm --module_path=/home/aachar/truckeasy/projectx-mirror/node_modules/osrm/lib/binding' (1)
make: *** [build] Error 1

**Comment by TheMarex** [comment]
@payanacloud What are you trying to do here? If you do `npm install osrm` you should be good, since there are binary packages for your distribution.

If you want to install `osrm-backend` use [this repository](https://github.com/Project-OSRM/osrm-backend) and [this guide](https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu).

**Comment by payanacloud** [comment]
Wanted to be able to query for routes. As I understood the procedure first we install node osrm and then we need to prepare the osrm file. The wiki calls this the "Setup" step and tells us to run the make file. The make file seems to git clone the repository and then builds the osrm backend code and also downloads the pbf file and runs extract and prepare. So I figured the make sets everything up to finally query for routes. Please correct me if I am wrong.

**Comment by TheMarex** [comment]
@payanacloud the binaries you need are in `node_modules/osrm/lib/binding/`. You'll find `osrm-extract` and `osrm-prepare` which can be used to prepare the data.

**Comment by payanacloud** [comment]
Figured that out. Thanks @TheMarex . I was under the impression that there were more things to be setup.
