### ISSUE TITLE
Latest nvm doesn't work with current Travis build scripts

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/node-osrm#139]
Looks like the HEAD version of nvm (as downloaded here: https://github.com/Project-OSRM/node-osrm/blob/develop/scripts/install_node.sh)

no longer works the same, and causes Travis builds to fail (example: https://travis-ci.org/Project-OSRM/node-osrm/jobs/104184219#L272)

We have two options:

  1 - Pin that checkout to a previous version that's known to work.
  2 - Update our build scripts to work with the latest code.

Anyone have a preference?

**Comment by TheMarex** [comment]
We fixed this by checking out a fixed version.
