### ISSUE TITLE
Distance matrix calculations with a lot of locations rans node out of memory

### ISSUE THREAD

**Issue by stepankuzmin** [Project-OSRM/node-osrm#145]
Hi there! I've tried to calculate a large distance matrix (~121 049 points) using following code

```js
osrm.table({ coordinates: points }, function(error, table) {
  if (error) {
    callback(error)
  } else {
    callback(null, table)
  }
})
```

And process ran out of memory. How can I deal with large amount of points?

**P.S.** OS X 10.11.3, node 5.5

**Comment by TheMarex** [comment]
How much main memory is available? Remember this is a significant number of points that is _squared_ and for each entry in the matrix there is a certain memory overhead in the computation.

**Comment by danpat** [comment]
Just to highlight @TheMarex 's point: you are calculating 14,652,860,401 routes.  Each distance result is a 32bit integer, so you'll need at least 58,611,441,604 (55GB) of RAM, and that's assuming that there's no overhead in the returned data structure (hint: there is).

If you don't have a machine with that amount of memory available, you will need to break your request down into multiple smaller requests and combine the results in a separate process.

**Comment by stepankuzmin** [comment]
Thanks for reply @TheMarex and @danpat!

So, I need to split points into some combinations of limit size, pass them through osrm.table and build whole distance matrix with results. Is that correct?

**Comment by stepankuzmin** [comment]
If anyone interested in this feature, I've made simple package for that case — https://github.com/stepankuzmin/distance-matrix
