### ISSUE TITLE
Move API docs to documentation.js

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#149]
Task is to convert https://github.com/Project-OSRM/node-osrm/blob/develop/API.md to documentation.js

Actionable:
 - Move docs for specific functions into the doc
 - Add key deps for parsing those docstrings
 - Add developer docs about how to document new code

Not yet actionable
 - publishing - we'll need to scheme a place first which depends on decisions at #126

**Comment by mapsam** [comment]
Looks like @morganherlocker took this idea for a spin a while back, but ran into some blockers with documentationjs. Seems like those blockers are no longer an issue, and the PR could be revisited. https://github.com/Project-OSRM/node-osrm/pull/102

**Comment by mapsam** [comment]
Let me know if you'd like a ✋ @morganherlocker!

**Comment by morganherlocker** [comment]
> Let me know if you'd like a :hand: @morganherlocker!

Would love a hand. I believe the file linked by @springmeyer was actually generated with documentation.js, although it looks like it has since been deleted. I am not sure what has changed since I added annotations, but if you kick things off, I'm happy to lend a second set of eyes to the source.

**Comment by springmeyer** [comment]
@mapsam - sounds great to get this set up. As far as content make sure to check with @TheMarex on next actions because the OSRM v5 API has changed quite a bit recently.

**Comment by TheMarex** [comment]
@mapsam @morganherlocker current API docs live in the [wiki](https://github.com/Project-OSRM/osrm-backend/wiki/node-osrm-api). Would be great if we could move this in-repository with `documentation.js`.

**Comment by mapsam** [comment]
@morganherlocker taking a look at this now. Looks like a [blocker of yours last time](https://github.com/Project-OSRM/node-osrm/pull/1020) was being unable to "group items within the OSRM class together; move typedefs for result objects to the bottom". Here's a quick screenshot of an example I'm seeing - is this the desired order?

<img width="949" alt="screen shot 2016-05-02 at 9 42 32 am" src="https://cloud.githubusercontent.com/assets/1943001/14960576/310775f6-104a-11e6-8baa-2243e710ff53.png">

Still haven't gotten the `return {MatchResult}` linkages to work, but think it's probably user error.

**Comment by TheMarex** [comment]
@mapsam which branch are you working of? This looks like the old API to me. :-) You should base this on `master` and try to adapt https://github.com/Project-OSRM/osrm-backend/wiki/node-osrm-api Let me know if you hit any walls. Happy to help.

**Comment by mapsam** [comment]
@TheMarex 🙏 thank you for pointing that out. Probably going to start fresh. I'll keep peaking at @morganherlocker's branch to confirm we can bypass some of the blockers he encountered though.

My plan (happy to adapt):

- [ ] move all docs (verbatim) from [the wiki](https://github.com/Project-OSRM/osrm-backend/wiki/node-osrm-api) into documentation.js format. 
- [ ] figure out best way to highlight "general options" throughout the methods (probably link to an `@options` class?)
- [ ] properly link response objects to their methods
- [ ] get example response JSONs to add to response docs
- [ ] expand on `OSRM` class for overall usage and description of `.osrm` databases (probably best for a separate page at some point?)

**Comment by mapsam** [comment]
I made some good progress today, working through a new theme for the node-osrm docs and transferring docs from the wiki into docs.js. I'll pause here to get some feedback from @TheMarex. 

@TheMarex what do you think about hosting a documentation.js theme for OSRM on the organization github, something [similar to Node Mapnik](https://github.com/mapnik/node-mapnik-theme)? Is building out a theme worthwhile?

Where is the documentation for generating a `.osrm` file (like most of the examples reference - `berlink_roads.osrm`)? This may be helpful to at least link to from the docs.

Screenshot of the theme so far (doing my best to grab colors/fonts from `project-osrm.org`:

<img width="797" alt="screen shot 2016-05-02 at 4 12 02 pm" src="https://cloud.githubusercontent.com/assets/1943001/14970845/58a9e4f4-1081-11e6-8350-743d06e0240e.png">

**Comment by morganherlocker** [comment]
> Where is the documentation for generating a .osrm file (like most of the examples reference - berlink_roads.osrm)? This may be helpful to at least link to from the docs.

[The OSRM wiki](https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM#how-to-run-the-tool-chain) has the most comprehensive rundown for indexing the graph.

**Comment by mapsam** [comment]
After discussion with @TheMarex, here are the next steps:

* finish writing up JSDOC
* generate `docs/api.md` file in this repo using documentation.js `-markdown` flag
* make that generation as simple as possible (automated or a single command) so keeping things up-to-date is simple (maybe via `npm docs` or `npm test`?)

I'm going to hold on:

* developing the theme (but I'll keep it around for whenever it's needed) - for now having documentation as a markdown file in the repo is just fine

**Comment by mapsam** [comment]
Just completed the full transfer from the wiki to JSDOC. A couple take-aways:

* there are still some oddities when linking classnames in documentation.js `--polyglot` mode, so links aren't as smart as I'd hope - but still work! For example: instead of writing `{@link OSRM.route}` we have to write markdown links `[OSRM.route](#route)`. Since there aren't many changing methods in node-osrm, I don't think this is a big concern.
* The "return" statements are a little wonky, mostly because documentation.js doesn't **bold** the header, so they don't stand out as much. 
* I think having JSON example responses is super useful (like [`Route`](https://github.com/Project-OSRM/node-osrm/blob/docsjs/docs/api.md#route-1)) - it would be great to get more of these. 
* The API docs are now in `docs/api.md`, which gives space for more files such as `GETTING_STARTED.md` and `INSTALLATION.md`, which could make the README a bit smaller

Here's the [current example output](https://github.com/Project-OSRM/node-osrm/blob/docsjs/docs/api.md) when running `documentation build src/node_osrm.cpp --polyglot -f md -o docs/api.md`. @TheMarex want to have a look?

Right now running the above command is pretty simple, but requires `npm install -g documentation`. Do we want `documentation` be a `devDependency` or should it remain globally installed on our individual computers?

**Comment by TheMarex** [comment]
@mapsam this looks great!

Some minor formatting errors like at the enumeration at the `Return` of `match` https://github.com/Project-OSRM/node-osrm/blob/docsjs/docs/api.md#match

> Do we want documentation be a devDependency or should it remain globally installed on our individual computers?

`devDependency` + trigger over `npm run docs` would be great.

**Comment by mapsam** [comment]
> minor formatting errors like at the enumeration

Unfortunately the "returns" section is pretty strict - I've tried to get bullet points and enumeration to work without any luck. The markdown renderer is trying its best to keep everything as as single paragraph. I'll try out some options.

**Comment by springmeyer** [comment]
> Do we want documentation be a devDependency or should it remain globally installed on our individual computers?

This is a really heavy dependency and I've seen it slow down travis runs. So @TheMarex unless we want to run `npm run docs` on travis each time I'd recommend holding back from being a `devDependency`. Unless something has changed and it has fewer slow to install deps. My memory is vague but I think it was adding at least 30s last time I tried this with node-mapnik (> 1 year ago).

**Comment by TheMarex** [comment]
> adding at least 30s last time

I'm okay with spending 30 seconds in favor of having building docs easy and documented in the place you would expect.

@mapsam how is it going? Want to open a PR?

**Comment by springmeyer** [comment]
> I'm okay with spending 30 seconds in favor of having building docs easy and documented in the place you would expect.

@mapsam if it turns out to be more than that, perhaps a hack to satisfy both concerns of:

 - 1) not slowing down travis builds by devDeps that are not needed and
 - 2) making it easy for anyone to build the docs

Would be to add a `npm run docs` target that instead of the normal:

```js
  "scripts": {
    "docs": "documentation src/*.cpp --polyglot -o documentation -f html --github --name <project name>"
  }
```

Does:

```js
  "scripts": {
    "docs": "npm install documentation && documentation src/*.cpp --polyglot -o documentation -f html --github --name <project name>"
  }
```

**Comment by springmeyer** [comment]
@TheMarex - looks like this is merged in now, thank you. Can this be closed up now?

**Comment by TheMarex** [comment]
Yes this is merged.
