### ISSUE TITLE
Don't have travis build binaries on "pr" tests

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/node-osrm#158]
When pushing to a PR triggers two travis builds:

- The **push**: as you'd expect, this is the HEAD of the branch that you just pushed
- The **pr**: this is the state of *the base branch* if the branch were to merge

This introduces an annoying race condition for commits with the `[publish binaries]` flag. Travis builds the binaries for the **push** and publishes them. Then it tries to do it again for the **pr** build, but this fails because the binaries already exist. :face_with_rolling_eyes:

![](https://dl.dropboxusercontent.com/s/5i3ptb3vkh1hgjn/2016-02-26%20at%2012.11%20PM.png?dl=0)

![](https://dl.dropboxusercontent.com/s/erlpnyns2j8v1qp/2016-02-26%20at%2012.17%20PM.png?dl=0)

We [tried to work around this by disabling branch builds](https://github.com/Project-OSRM/node-osrm/pull/151#issuecomment-189098356), but this is a major inconvenience and point of confusion because:

- Your branch will only be tested if a PR is opened against either the `master` or `develop` branch
- It is only possible to publish binaries using PRs against either the `master` or `develop` branch. This leads to [confusing dev PRs that we never intend to merge](https://github.com/Project-OSRM/node-osrm/pull/134)
- When you do this, the published binary will not actually represent your branch - it will be the merge of your branch with the base branch of the PR

Can we fix this by having travis refuse to build binaries of the **pr** build?

/cc @springmeyer

**Comment by willwhite** [comment]
It looks like there was [some effort](https://github.com/Project-OSRM/node-osrm/pull/143) to fix this by skipping the publish step on the **pr** build. @freenerd any idea why this isn't working?

**Comment by freenerd** [comment]
@willwhite #143 was specifically for enabling PR builds again (by skipping the merge commit to look for _publish binaries_ in the next commit). We could never publish binaries on PRs by bailing when we find a merge commit at head.

**Comment by springmeyer** [comment]
I'm putting this in my queue to look into. /cc @willwhite @lbud
