### ISSUE TITLE
Try testing/building on Circle CI

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#162]
Ticket to track whether we can use circle ci for linux builds (we'd keep using travis for osx builds). Assigning to myself to look into this.

The question has come up of whether circle ci has recent enough compilers.

 - Currently we are using g++-4.8 on travis (https://github.com/Project-OSRM/node-osrm/blob/develop/.travis.yml#L15). 
 - Soon we'll need g++-5 for c++14 support (#153)

/cc @willwhite @lbud @TheMarex @daniel-j-h

**Comment by daniel-j-h** [comment]
The blockers for node-osrm are likely the same as for osrm-backend? It would be great to know if we can run both node-osrm and osrm-backend builds on Circle CI.

**Comment by springmeyer** [comment]
Update here: I've been experimenting with circle ci and have found that:

  - it is possible to upgrade compilers since you have sudo
  - machines as precise by default, but can opt-in for trusty (like travis)
  - builds start very very quickly
  - compile performance is similar to travis
  - circleci supports caching, so ccache works great
  - circle ci supports either OS X or linux, but not both.
  - Their free plan supports one linux build, anything more (concurrent builds, or OS X) cost $$$

I have a personal testing trial account currently ($30/month) to be able to test OSX builds. My next action is to get both node-osrm and osrm-backend building with circleci. Depending on how things work, then I'll assess whether it is worth the $$$ (likely).

**Comment by willwhite** [comment]
Link to [brochure page about osx support](https://circleci.com/mobile/osx/).

> circle ci supports either OS X or linux, but not both.

The restriction is per repo? This means we'd still have to use travis for either OSX or Linux?

We already have a $$ account at Mapbox. If this just means setting another one up for the OSRM group I'm :+1: on this plan.

**Comment by springmeyer** [comment]
> The restriction is per repo? This means we'd still have to use travis for either OSX or Linux?

Yes, per repo. So a given circle-enabled repo can only build on OS X or Linux and not both.

> We already have a $$ account at Mapbox. If this just means setting another one up for the OSRM group I'm 👍 on this plan.

Circle allows "piggybacking" one org on another. I've just enabled the `Seed` plan for OS X for the Mapbox account and worked with @TheMarex to get node-osrm enabled for circleci os x using this. https://circleci.com/gh/Project-OSRM/node-osrm.

Next actions are:

  - [ ] Actually start building the code (current scripts are just a stub)
  - [ ] Watch the demand and figure out if a `Seed` plan is enough
  - [ ] Once farther along and proven, hook up publishing on circleci and disable the travis OS X jobs

**Comment by springmeyer** [comment]
> Watch the demand and figure out if a Seed plan is enough

Used 9% so far for the month: (43/500 minutes). Seems reasonable for now to go forward with.

> Once farther along and proven, hook up publishing on circleci and disable the travis OS X jobs

Tracked at #221

Closing as per #220
