### ISSUE TITLE
Issues with v5.0.0-newapi.4

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/node-osrm#165]
I'm seeing funny results coming out of the [v5.0.0-newapi.4 build](https://github.com/Project-OSRM/node-osrm/releases/tag/v5.0.0-newapi.4). 

#### Staying on the same street
On a route that travels on one street for a little while, I'm seeing some redundant steps that read like I'm getting steps per node rather than per way and intersection. With this query for example,
> http://localhost:8080/directions/v5/mapbox/driving/-6.777998507022858,62.012826847473846;-6.774841547012329,62.01047300499044

I'm seeing results like https://gist.github.com/karenzshea/0a4e8a3af347f0c07d6a
For example, four almost identical steps are returned in a row like this one below, but with their respective geometry segments that make up the osm way.
```
"maneuver": {
	"bearing_after": 151.77143695867963,
	"bearing_before": 154.4174453761233,
	"location": [-6.777229,
		62.012197
	],
	"modifier": "straight",
	"type": "new name",
	"instruction": "Go straight onto Tróndargøta, Tróndargøta becomes Tróndargøta"
},
"mode": "driving",
"duration": 2.4,
"name": "Tróndargøta",
"distance": 33.3274097811409
}
```
For comparison, the same route returned by the build before this v5.0.0-newapi.3 are here https://gist.github.com/karenzshea/0069f2720b5b3a15e31a

---

#### Roundabouts and traffic circles

In this query,
>  http://localhost:8080/directions/v5/mapbox/driving/7.41600751876831,43.73101088081149;7.418469786643982,43.73208072770532

I'm seeing steps for roundabout and traffic circle that either feel redundant or should be condensed into one step. 
The first step below for example includes what I think is an unnecessary exit. In the second step, the modifier `right` of the traffic circle step is unnecessary - unless there are traffic circles in the world that people exit on the left?

This could read more like "enter the roundabout Rond-Point Canton and take the first exit onto Boulevard Charles III." The difference here between `v5.0.0-newapi.3` and `4` is that the name of the roundabout wasn't previously included. 
```
{ "geometry": "ei|iGatgl@D?BCDC@EBG?GAIAGCEECEAEAEBCB",
"maneuver": {
	"exit": 1,
	"bearing_after": 170.53298550318837,
	"bearing_before": 50.85203399925292,
	"location": [
		7.417126,
		43.731546
	],
	"modifier": "right",
	"type": "roundabout",
	"instruction": "Enter the roundabout and take the first exit onto Rond-Point Canton"
},
"mode": "driving",
"duration": 4.7,
"name": "Rond-Point Canton",
"distance": 47.035190951849
}, {
	"geometry": "si|iGwugl@KQCK",
	"maneuver": {
		"bearing_after": 46.3016858529149,
		"bearing_before": 329.5115510310183,
		"location": [
			7.417401,
			43.731624
		],
		"modifier": "right",
		"type": "traffic circle",
		"instruction": "At the traffic circle, make a right onto Boulevard Charles III"
	},
	"mode": "driving",
	"duration": 5.5,
	"name": "Boulevard Charles III",
	"distance": 14.74535600367225
}
```

@TheMarex @MoKob I hope this is helpful for debugging, esp on the guidance side? These could potentially be turned into test cases of some kind for osrm-backend.

**Comment by karenzshea** [comment]
:tada: I just generated my test data wrong :blush: the binaries work great

**Comment by MoKob** [comment]
@karenzshea on left sided traffic, round-about should also go the other way, so you would exit to the left and enter to the left as well, wouldn't you?
