### ISSUE TITLE
Utilize CMAKE_SHARED_LINKER_FLAGS

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#172]
When/if we pass custom linker flags to OSRM build we need to be careful to pass them to both the command line tools and libosrm.

TODO: 
- [ ]  @springmeyer tests using CMAKE_SHARED_LINKER_FLAGS

refs https://github.com/Project-OSRM/node-osrm/pull/168#discussion_r56625848

**Comment by daniel-j-h** [comment]
Giving it a try in https://github.com/Project-OSRM/node-osrm/pull/261.
