### ISSUE TITLE
Tests failing on develop branch

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/node-osrm#173]
Tests are failing on the develop branch: https://travis-ci.org/Project-OSRM/node-osrm/builds/116967833. Need to dig into why.

**Comment by springmeyer** [comment]
Just seeing this now. @willwhite - the build you link to above looks cancelled not failing. I'm going to close because we are green as of now: https://travis-ci.org/Project-OSRM/node-osrm/builds/119137839
