### ISSUE TITLE
Debug builds are publishing binaries with Release in the name

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/node-osrm#174]
A recent build (a Debug build):

https://travis-ci.org/Project-OSRM/node-osrm/jobs/118245846#L2662

published Debug binaries at the Release path on S3.  This caused some confusion downstream.  Looks like `node-pre-gyp` isn't getting the release name properly?

/cc @TheMarex @springmeyer

**Comment by springmeyer** [comment]
Thanks for catching this. This regressed about a month ago (https://github.com/Project-OSRM/node-osrm/commit/2f3422013ba2b4dbf90fdd01d4725c15c41f81d1) when I removed the passing of options to node-pre-gyp that I thought were not needed (but they are). Working up a fix now.

**Comment by danpat** [comment]
Hmm, looks like something is still funny.  A recent debug build on Linux complained that it couldn't publish to S3 because there was something already in the way.  The Debug build has "Release" in the path name it generates:

https://travis-ci.org/Project-OSRM/node-osrm/jobs/122648603#L1813

**Comment by danpat** [comment]
Woop, nevermind, looks like an error in the `.travis.yml` file here:  https://github.com/Project-OSRM/node-osrm/blob/develop/.travis.yml#L51-L52

**Comment by danpat** [comment]
Fixed with a3878cc935ba597004b2cd084c5cb078aead638c
