### ISSUE TITLE
waypoints optimization

### ISSUE THREAD

**Issue by smolleyes** [Project-OSRM/node-osrm#179]
hi

can we use osrm (and/or this node lib) to for exemple

get a waypoints list from kml or somewhere else with start/end waypoints and many waypoints then let osrm reorganize it to get the shortest route with reordered waypoints?

thanks !

**Comment by danpat** [comment]
@smolleyes Yes, the `trip` plugin does this.  However, it can only do return-to-the-same-point optimization at the moment, you can't specify the start/end point.

**Comment by smolleyes** [comment]
ok thanks for the fast reply i use the tspsolver.js for the moment with good results but stay up to date on others solutions, will follow the dev here :)
