### ISSUE TITLE
Binaries for 5.1.0 not released for npm?

### ISSUE THREAD

**Issue by chr4** [Project-OSRM/node-osrm#188]
Despite a promising [commit message](https://github.com/Project-OSRM/node-osrm/commit/85978396b3ae78616fca3e0164042220f0fa500c) I'm getting the following error on `npm install osrm`:

```
node-pre-gyp ERR! Tried to download: https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.1.0/Release/node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for osrm@5.1.0 and node@6.1.0 (node-v48 ABI) (falling back to source compile with node-gyp)
```

I'm using node v6.1.0 and npm 3.8.6.
Hints apprechiated!

**Comment by danpat** [comment]
Unfortunately, C++ binary publishing for Node requires us to do a build against each Node version we support, and publish a binary for that.

Thus, you'll only get binaries for a Node version once we add it to our build list (see https://github.com/Project-OSRM/node-osrm/blob/master/.travis.yml#L27-L60).

We currently are only publishing binaries for Node 4.  I'm sure we'll get to Node 6 in the future, but right now, it's not really on the radar.  Patches accepted of course!

I have no idea if any code changes are required for Node 6, I don't think any of us has really looked at it.

Short-term workaround for you would be to use `nvm` to install Node 4.

**Comment by chr4** [comment]
Thanks, using node-4 as a workaround fixes this.
