### ISSUE TITLE
Fix failing compile for debug linux builds

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#191]
The debug builds on linux are failing currently with https://gist.github.com/springmeyer/57ce8a5c6f52fc1d5bf264bfa6e5ecc0 after new use of interprocess: https://github.com/Project-OSRM/osrm-backend/pull/2412.

Likely cause is either a boost bug or [a g++ 4.8 LTO bug](https://github.com/mapnik/mapnik/issues/2238). First plan will be to try to upgrade boost.

**Comment by springmeyer** [comment]
> First plan will be to try to upgrade boost.

Upgrading to boost 1.61.0 triggers new compile errors: https://gist.github.com/springmeyer/6fecbf2bf9736eb23dadc68a4919e1c7

**Comment by springmeyer** [comment]
> Upgrading to boost 1.61.0 triggers new compile errors: https://gist.github.com/springmeyer/6fecbf2bf9736eb23dadc68a4919e1c7

Testing workaround at https://github.com/Project-OSRM/osrm-backend/pull/2427. Thanks @daniel-j-h for the help on this!

**Comment by springmeyer** [comment]
Turns out upgrading boost did not fix this.

> Likely cause is either a boost bug or a g++ 4.8 LTO bug. First plan will be to try to upgrade boost.

So, that means this is only a g++ LTO bug. Next action for me is to disable the LTO to confirm /cc @TheMarex @daniel-j-h

**Comment by springmeyer** [comment]
> So, that means this is only a g++ LTO bug.

Wait, can't be since this is the Debug build failing and I think we don't set LTO in Debug mode. Will keep on digging...

**Comment by springmeyer** [comment]
Further narrowed this down: only replicates on precise and not trusty.

**Comment by springmeyer** [comment]
Replicates on precise with this command:

```
ccache /usr/bin/g++-4.8   -DBOOST_ENABLE_ASSERT_HANDLER -DBOOST_FILESYSTEM_NO_DEPRECATED -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_SPIRIT_USE_PHOENIX_V3 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-inline -fno-omit-frame-pointer -Og -ggdb -Wall -Wextra -pedantic -Wuninitialized -Wunreachable-code -Wstrict-overflow=1 -D_FORTIFY_SOURCE=2  -fPIC -ffunction-sections -fdata-sections -std=c++11  -fopenmp -g -I/home/ubuntu/node-osrm/deps/osrm-backend-Debug/include -I/home/ubuntu/node-osrm/deps/osrm-backend-Debug/build/include -isystem /home/ubuntu/node-osrm/deps/osrm-backend-Debug/third_party -isystem /home/ubuntu/node-osrm/deps/osrm-backend-Debug/third_party/libosmium/include -isystem /home/ubuntu/node-osrm/mason_packages/.link/include -isystem /home/ubuntu/node-osrm/mason_packages/.link/include/luabind    -o CMakeFiles/CONTRACTOR.dir/src/contractor/contractor.cpp.o -c /home/ubuntu/node-osrm/deps/osrm-backend-Debug/src/contractor/contractor.cpp
```

Taking out the `-fno-inline` solves the issue.

**Comment by springmeyer** [comment]
This also works around:

```
--- /home/ubuntu/node-osrm/mason_packages/.link/include/boost/interprocess/detail/os_file_functions.hpp_	2016-05-20 20:50:48.520618738 +0000
+++ /home/ubuntu/node-osrm/mason_packages/.link/include/boost/interprocess/detail/os_file_functions.hpp	2016-05-20 20:53:22.616630251 +0000
@@ -468,7 +468,7 @@
    (const char *name, mode_t mode, bool temporary = false)
 {
    (void)temporary;
-   return ::open(name, (int)mode);
+   return ::open(name, (int)mode,S_IRUSR|S_IWUSR);
 }
 
 inline bool delete_file(const char *name)
```

**Comment by daniel-j-h** [comment]
Interesting, what's the problem with `open`?
