### ISSUE TITLE
Nightly builds on Travis

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/node-osrm#203]
We have [cron jobs](https://docs.travis-ci.com/user/cron-jobs/) enabled for the Project-OSRM org on Travis now. This would hopefully lead to faster development and earlier detection of breaking binary build process.

We can use these to build nightly builds.
- Enable cron on the `master` branch
- Detect via `TRAVIS_EVENT_TYPE` that it's a cron execution
- Build binaries
- Decide on good name, maybe `semver-nightly-date` would be enough? Or without semver at all?

Also we could think about the demoserver using these nightly builds.

/cc @TheMarex @springmeyer @daniel-j-h

**Comment by springmeyer** [comment]
Noting that we have crons enabled now on node-osrm master:

![screen shot 2016-09-08 at 12 08 45 pm](https://cloud.githubusercontent.com/assets/20300/18362999/0cd12fd2-75bd-11e6-90d0-0fe9713f3278.png)

Automatically publishing binaries is still something we could consider. @danpat and I chatted about this a while back and figured we could have a branch run on a cron that actually publishes a differently named package called `osrm-latest`. This branch would then overwrite its binaries nightly using `node-pre-gyp unpublish publish`. So if you wanted to get the latest always you could use `"osrm-latest":` in your package.json.

**Comment by springmeyer** [comment]
obsolete per #307
