### ISSUE TITLE
zlib.h not found on make

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/node-osrm#211]
When cloning a fresh version of node-osrm and calling make, I see the following error:

Can't find header file /Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/zlib.h

Even though this error occurs, the build itself seems to succeed. Still, the presence of this message indicates something might be off?

/cc @springmeyer

**Comment by springmeyer** [comment]
> Can't find header file /Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/zlib.h

Thanks for flagging. This may be a mason issue that manifests on OS X 10.10. I presume others are not seeing this because we are running 10.11. I'm on vacation this week starting today: @jfirebaugh and @kkaefer can help with mason issues while I'm away.

refs https://github.com/mapbox/mason/blob/master/scripts/zlib/system/script.sh#L32-L35

**Comment by springmeyer** [comment]
@MoKob - Can you please share a few details of your system?

 - What OS X version?
 - What does this command give? `xcode-select -p`
 - What does this command give? `xcrun --sdk macosx --show-sdk-version`

**Comment by MoKob** [comment]
@springmeyer 

* osx: 10.11.5 (15F34)
* ```xcode-select -p : /Library/Developer/CommandLineTools```
* ```xcrun --sdk macosx --show-sdk-version : 10.11```

**Comment by MoKob** [comment]
For documentation: `xcrun --sdk macosx --show-sdk-path` provided an empty output.
After a re-installation of xcode via the app-store, the error is gone and `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk` is now the output of the command.

Seems like it was the result of a broken `xcode` installation.
