### ISSUE TITLE
Fingerprint of ./test/data/berlin-latest.osrm.icd does not match or could not read from file

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#224]
Just started seeing this on OS X/Circleci today (not seeing on travis osx):

```
[info] load names from: "./test/data/berlin-latest.osrm.names"
[info] name offsets size: 1841
[warn] caught exception: Fingerprint of ./test/data/berlin-latest.osrm.icd does not match or could not read from file
make: *** [shm] Error 1
```

https://circleci.com/gh/Project-OSRM/node-osrm/56

Probably something wrong with circleci, not node-osrm. But @TheMarex @daniel-j-h  any hints on how to debug?

**Comment by daniel-j-h** [comment]
Probably a caching-related issue. I think these two lines are potentially dangerous:

- https://github.com/Project-OSRM/node-osrm/blob/ee405f3b959d217bcf04dd89fa23da60e20ddc18/.travis.yml#L16
- https://github.com/Project-OSRM/node-osrm/blob/master/circle.yml#L13

`test/data` contains the generated `*.osrm` data files. If you cache those, too, changes to osrm's data format (e.g. as in [this commit to osrm-backend master](https://github.com/Project-OSRM/osrm-backend/commit/ee47afbe17ba515de785c92a06cf10a150fd0821) today) have to invalidate the cache (somehow).

**Comment by springmeyer** [comment]
> Probably a caching-related issue

It was, thank you @daniel-j-h. The reason this happened on circle and not travis is that circle pulls from the latest cache for branches/PR whereas Travis creates a cache from scratch on branches. For now I've rebuild the circleci build without a cache and it passes fine.

**Comment by springmeyer** [comment]
> Travis creates a cache from scratch on branches

And then travis failed when I rebased of course :) Because the data format change came into the branch after the cache had been created.

So, fundamentally this seems like it needs to be fixed in osrm-backend: when the data format is changed we need a way to know to alert developers and travis/circleci to clear their `test/data` cache.

**Comment by daniel-j-h** [comment]
> So, fundamentally this seems like it needs to be fixed in osrm-backend: when the data format is changed we need a way to know to alert developers and travis/circleci to clear their test/data cache.

If you run on `osrm-backend` master there are no guarantees towards data format. It's a bad idea to cache the `*.osrm` files not only because of this, but also because our tests then no longer actually run `osrm-extract` or `osrm-contract` to generate those files, leaving their code paths untested.

What I would do: cache the `*.osm` extracts in the `test/data` directory so we don't have to download them every time. Do not cache any other files in `test/data`.

**Comment by springmeyer** [comment]
Fixed in https://github.com/Project-OSRM/node-osrm/commit/92c491b249c6004a83b6647371de1a5bedb30ff1. I never intended to catch `test/data`: this was  a result of my confusing node-osrm with osrm-backend since I was working on each:

 - `osrm-backend` supports the `test/cache` directory which can and should be cached between runs to speed up `osrm-backend` cucumber tests
 - `node-osrm`'s `test/data` directory is not intended to be cached between runs in the same way. As @daniel-j-h notes some files could be cached, but that would need further testing to ensure a benefit and I doubt it would.
