### ISSUE TITLE
How to calculate state miles.

### ISSUE THREAD

**Issue by mdhanju** [Project-OSRM/node-osrm#236]
Any idea how to calculate state miles.
For example i travel from Los Angles to Dellas TX, need miles travelled in each state, CA, AZ, NM,  and TZ.

**Comment by daniel-j-h** [comment]
Sorry for the late response! You can do your route request with `node-osrm` but you have to do the post-processing yourself: one idea would be to check the coordinates for each step in the response against state polygons doing simple point-in-polygon tests.

Closing this as not actionable on our side.
