### ISSUE TITLE
OSX Travis builds are failing

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/node-osrm#245]
https://travis-ci.org/Project-OSRM/node-osrm/builds/161042964

Looks like brew is the reason for this, or updated Travis CI OSX environments, or both.
I only found some hacks requiring git pull'ing brew repositories.

@springmeyer could you look into this please? Would be great to have this fixed during the next days since we plan on doing the 5.4 release as soon as the last remaining issues are resolved.

cc @MoKob just in case we see this during release.

**Comment by springmeyer** [comment]
Solved by #246. Please rebase against master to get the fix.

**Comment by daniel-j-h** [comment]
Closing as solved! Thanks for the fix!
