### ISSUE TITLE
Mac OS X travis builds should fail on checksum mismatch

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/node-osrm#249]
Linux fails https://travis-ci.org/Project-OSRM/node-osrm/jobs/162779816#L2298

Mac OS X continues https://travis-ci.org/Project-OSRM/node-osrm/jobs/162779818#L2221

**Comment by daniel-j-h** [comment]
Related: https://github.com/Project-OSRM/node-osrm/pull/246 introduced a md5sum Node script:

https://github.com/Project-OSRM/node-osrm/blob/0934db21b66583b093908e0b32fde3ed4b3ab3c2/test/data/Makefile#L36.

But we still rely on the md5sum binary for generating the md5sum checksum file:

https://github.com/Project-OSRM/node-osrm/blob/0934db21b66583b093908e0b32fde3ed4b3ab3c2/test/data/Makefile#L47

**Comment by springmeyer** [comment]
Fixed by #258
