### ISSUE TITLE
Inconsistent tile size on mac vs linux

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#263]
I'm seeing https://github.com/Project-OSRM/node-osrm/blob/08cc0cb4391168e617553eae8ce3aed463e7cf84/test/tile.js#L10 be 4 bytes smaller on linux (seen in local docker image) than OS X while working on #258.

Will need to figure out if this is a sign of a bug, or something expected that we'll need to adjust the test for.

/cc @danpat

**Comment by danpat** [comment]
@springmeyer Can you capture the tiles, convert to geojson and compare to see what feature is missing?

**Comment by springmeyer** [comment]
@danpat:

  - osx: https://gist.github.com/springmeyer/bfbac3b3783efc4ca5254524c0021bfa
  - linux: https://gist.github.com/springmeyer/25ec872d83835d6b6f99d7aaaa9c9bda

**Comment by daniel-j-h** [comment]
What's the state of this? Especially in the context of our planned 5.5 release in the coming days.

**Comment by danpat** [comment]
https://github.com/Project-OSRM/osrm-backend/issues/3343

**Comment by springmeyer** [comment]
Solved by https://github.com/Project-OSRM/osrm-backend/pull/3393

**Comment by springmeyer** [comment]
TODO:

  - Make this check strict again: https://github.com/Project-OSRM/node-osrm/blob/bd968b9ed625564ab2234a054b8f0cd66afadc68/test/tile.js#L10

**Comment by springmeyer** [comment]
Remaining todo moved to https://github.com/Project-OSRM/osrm-backend/issues/4177
