### ISSUE TITLE
md5sum frequently needs update in master

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#265]
After https://github.com/Project-OSRM/node-osrm/commit/35ab4708d94dfffe110b1fb047aec24133f471df we now build against osrm-backend `master` for commits to node-osrm `master`.

I think this setup is good, but there is one drawback: changes to the profiles break node-osrm test data setup because we assert against a checksum stored inside node-osrm. Just this week there have been several profile changes merged into osrm-backend master: https://github.com/Project-OSRM/osrm-backend/commits/master/profiles so it is expected that node-osrm will be broken daily.

Possible ways to keep data integrity checks (for when they count) but reduce this friction:
- Ignore data integrity checks for node-osrm builds against osrm-backend `master`, but continue asserting when building against an osrm-backend tag or other release
- Generate the md5sum file in osrm-backend and allow node-osrm builds to download it to assert
- Other ideas?

/cc @TheMarex @daniel-j-h @karenzshea

**Comment by daniel-j-h** [comment]
Related: once we ship profiles (https://github.com/Project-OSRM/node-osrm/pull/260) we no longer have to download them in the test directory. Taking profiles directly from the osrm-backend installation directory should solve this problem.

**Comment by springmeyer** [comment]
> we no longer have to download them in the test directory. 

Except in the case of building against an external osrm-backend, which is something @TheMarex does (and likely others).

**Comment by danpat** [comment]
Other idea: I know it's been discussed to death already, but: move `node-osrm` into `osrm-backend`.  NodeJS is now required by `osrm-backend` to run tests, so it's only a small step to including `nan`.

This would prevent profile duplication, and simply the build/release process.

**Comment by springmeyer** [comment]
obsolete per #307
