### ISSUE TITLE
Autopublish on for every tag

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/node-osrm#270]
mapbox-gl-native publishes a binary automatically for every tag if the tag name matches the version in `package.json`.

This could remove the need for `[publish binary]` commits and streamline the release process.

**Comment by daniel-j-h** [comment]
Stale. We do this with Docker images by now so that we don't have to build them ourselves every time we push a tag. Feel free to re-open in the backend if you still want to see this happening.
