### ISSUE TITLE
Architecture optimized binaries

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/node-osrm#276]
To use advanced instruction-sets like AVX we need to know about the target architecture more then `x86-64`. If we extend the architecture name by including target specific features such such AVX, SSE3 etc we could utilize this.

An alternative would be to explore using https://lwn.net/Articles/691932/ for specific key function (everything related to our geometric code for example).

**Comment by daniel-j-h** [comment]
=> https://github.com/Project-OSRM/osrm-backend/issues/4186
