### ISSUE TITLE
osrm-extract error - attempt to call global 'canonicalizeStringList' (a nil value)

### ISSUE THREAD

**Issue by Damakshn** [Project-OSRM/node-osrm#278]
I installed node-osrm on Debian jessie, but i cannot process raw data form .osm.pbf file.
I use profile script car.lua and osrm-extract utility which goes with node-osrm.
Here is command output:
`sudo lib/binding/osrm-extract -p deps/osrm-backend-Release/profiles/car.lua siberian-fed-district-latest.osm.pbf`
`[info] Using script deps/osrm-backend-Release/profiles/car.lua`
`[info] Input file: siberian-fed-district-latest.osm.pbf`
`[info] Profile: car.lua`
`[info] Threads: 1`
`[STXXL-MSG] STXXL v1.4.1 (prerelease/Release)`
`[STXXL-ERRMSG] Warning: no config file found.`
`[STXXL-ERRMSG] Using default disk configuration.`
`[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0`
`[info] Parsing in progress..`
`[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)`
`[info] timestamp: 2016-12-01T20:38:02Z`
`[info] Found no exceptions to turn restrictions`
`terminate called after throwing an instance of 'osrm::util::exception' what(): ERROR occured in profile script: deps/osrm-backend-Release/profiles/car.lua:452: attempt to call global 'canonicalizeStringList' (a nil value)`

Is it a bug or I use wrong profile/utility/something else?

**Comment by daniel-j-h** [comment]
Are you sure your `osrm-extract` version is in sync with the profiles?

If you do `npm install osrm` you should get the profiles, too

    ./node_modules/osrm/lib/binding/osrm-extract --version

and check if there is

    ./node_modules/osrm/deps/osrm-backend-Release/profiles/car.lua

**Comment by daniel-j-h** [comment]
Closing as stale.

**Comment by bubnenkoff** [comment]
Same error:

```
C:\Windows\system32>D:\apps\osrm\osrm-extract -p "D:\apps\osrm\car.lua" --threads 1  D:\data\osm\2017\rupart\central-fed-district.osh.pbf
[info] Using script D:\apps\osrm\car.lua[0m
[info] Input file: central-fed-district.osh.pbf[0m
[info] Profile: car.lua[0m
[info] Threads: 1[0m
[info] Parsing in progress..[0m
[STXXL-MSG] STXXL v1.4.99 (prerelease/Release) (git 78dd7ec6e72d7d6ef1209e594fc08e3759af5099) + gnu parallel(__GLIBCXX__)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] Disk 'C:\Users\DBUBNE~1\AppData\Local\Temp\stxxl.tmp' is allocated, space: 1000 MiB, I/O implementation: wincall delete_on_exit queue=0 devid=0
[info] input file generated by osmium/1.5.1[0m
[info] timestamp: n/a[0m
[info] Found 3 turn restriction tags:[0m
[info]   motorcar[0m
[info]   motor_vehicle[0m
[info]   vehicle[0m
[31m[error] [exception] invalid location
[0m
[STXXL-ERRMSG] Removing disk file: C:\Users\DBUBNE~1\AppData\Local\Temp\stxxl.tmp
```

Latest bin (release) version for Windows.

**Comment by daniel-j-h** [comment]
@bubnenkoff how is this the same issue?

> [error] [exception] invalid location

Looks like a coordinate is out of bounds and libosmium throwing.

Please open a separate ticket and provide more details. This is not actionable for us.
