### ISSUE TITLE
Bundle osrm-unlock-all and other tools

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/node-osrm#284]
We bundle the datastore but not its helper binary `osrm-unlock-all`. We should otherwise users are helpless when it comes to unlocking the shm locks.

cc @springmeyer

**Comment by springmeyer** [comment]
👍  to bundling all the tools that get built. We used to do this [here](https://github.com/Project-OSRM/node-osrm/blob/cb9f80e5affb881de05dce3c0c3b4f372603ce18/bootstrap.sh#L57) but this changed in the move to node-cmake: https://github.com/Project-OSRM/node-osrm/commit/5667a3307e652dd2ec26bd6a743d71accbe53ec6#diff-af3b638bc2a3e6c650974192a53c7291R53. Perhaps we should move back to using a glob for all built tools?

**Comment by TheMarex** [comment]
This will be obsolete with 5.6 since #3528 adds the ability to remove shared locks.

**Comment by oxidase** [comment]
@TheMarex only `osrm-unlock-all` will be obsolete. Other tools are still ok

**Comment by oxidase** [comment]
Superseded by  #3577, functionality was moved to `osrm-datastore`. `-DBUILD_TOOLS` enables only `osrm-io-benchmark` tool.
