### ISSUE TITLE
macOS compilation issue with current osrm-backend master

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/node-osrm#289]
macOS debug builds fail on Travis with

```
/Users/travis/build/Project-OSRM/node-osrm/deps/osrm-backend-Debug/src/contractor/contractor.cpp:212:69: error: invalid use of non-static data member 'source'

        BOOST_ASSERT(file_id <= std::numeric_limits<decltype(Value::source)>::max());

                                                             ~~~~~~~^~~~~~
```

Upstream location: https://github.com/Project-OSRM/osrm-backend/blob/d129b0ef2439a7f8f7be79c12d9bc2f12d6691ee/src/contractor/contractor.cpp#L212

Travis log: https://travis-ci.org/Project-OSRM/node-osrm/jobs/193869384#L389-L390

Came in with https://github.com/Project-OSRM/osrm-backend/commit/71e7d6d6b8dc7f3a4e416ba23dcb59e595dca075#diff-5d25f965a92c5af3a4dfd03cf4f7616aR211

cc @oxidase

**Comment by daniel-j-h** [comment]
Seems like the issue is gone with an update to XCode 8.2 in https://github.com/Project-OSRM/node-osrm/issues/290 (different issue now, check the PR).

**Comment by oxidase** [comment]
@daniel-j-h I suppose it is due to reduced c++11 support in XCode 7.3, if it is required to use 7.3 version, i can change to an explicit constant 255.

**Comment by daniel-j-h** [comment]
Resolved. Closing.
