### ISSUE TITLE
Installation issues with node v4.2.6, npm v3.5.2

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/node-osrm#305]
@springmeyer tracking here to not lose sight of it.

I can see the following installation error for `npm install osrm`:

https://gist.github.com/anonymous/b1fed5f7116b3626bc367f5fc75f3f1f#file-log-txt-L12839-L12869

With the OSGeo default v4.2.6 and npm v3.5.2 versions.
Updating via `nvm` to latest v4 solve the issue.

To reproduce grab the image at https://live.osgeo.org/en/download.html and run with

    qemu-system-x86_64 -cdrom osgeo-live-10.0-amd64.iso -m 4096 -enable-kvm -boot d

**Comment by springmeyer** [comment]
@daniel-j-h per chat I think you should try bundling node-pre-gyp and see if that solves the issue. I've just added details to the node-pre-gyp readme on bundling. Can you take a look at https://github.com/mapbox/node-pre-gyp#1-add-new-entries-to-your-packagejson and: 1) see if bundling solves the problem, 2) review those docs or any missing details you see

**Comment by daniel-j-h** [comment]
We do this [in the backend](https://github.com/Project-OSRM/osrm-backend/blob/df000debe9c6df6c91cb0af32e92b97d0af42aaf/package.json#L55-L57) now. Closing here.
