### ISSUE TITLE
Deprecate repository

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/node-osrm#307]
We moved node-osrm into osrm-backend https://github.com/Project-OSRM/osrm-backend/issues/3183. Therefore this repository can be deprecated.

Todo:

- [x] Update Readme with deprecation notice https://github.com/Project-OSRM/node-osrm/issues/308
- [x] Assure that osrm-backend Readme correctly talks about node-osrm
- [x] Close all PRs and Issues, move relevant information over to osrm-backend

/cc @daniel-j-h @TheMarex

**Comment by daniel-j-h** [comment]
Done here.
