### ISSUE TITLE
report OSRM git hash

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#33]
node-osrm should be able to report the git hash of OSRM it is built against.

**Comment by TheMarex** [comment]
Can we make mason generate a file with the `OSRM_VERSION` environment variable that we include in `src/osrm.js`? We should overthink the API versioning in `osrm-backend` as well, going to cut a ticket in backend for that as well.

**Comment by springmeyer** [comment]
done in #97
