### ISSUE TITLE
return value of libOSRM

### ISSUE THREAD

**Issue by DennisOSRM** [Project-OSRM/node-osrm#39]
@springmeyer @jfirebaugh 

So far, libOSRM returns a JSON formatted return string. Would it make more sense in terms of efficiency, and the way NodeJS would like to have things, to return an object that has a certain interface that NodeJS can use. 

The idea is to expose some object with a well-known interface/structure that can be used in any subsequent transformation of the result. I'd like to save some time on (costly) string generation/duplication.

**Comment by TheMarex** [comment]
This is implemented in the v4.6.0 branch using a renderer that converts ```osrm::json::Object``` to
```v8::Object```.
