### ISSUE TITLE
"table" service to return distance and time matrix with routing options

### ISSUE THREAD

**Issue by joaopiopedreira** [Project-OSRM/node-osrm#77]
Hi,

I'm using this osrm module in my (meteor.js) routing app and It's been working fine.

I'm looking at extending the "table" service to give me not only the (driving) time matrix but also the distance matrix. I'm also thinking at including options before generating these matrices (basically, "avoidHighways" and "avoidTolls" will do at this stage).

I have some experience in javascript/nodejs, but limited experience in C++.

Would somebody point me in the right direction? 

Thanks.

**Comment by DennisOSRM** [comment]
https://github.com/Project-OSRM/osrm-backend/pull/1162 is tracking this. Further pointers are in the backend repository.
