### ISSUE TITLE
osrm.table does not work in version 4.5 

### ISSUE THREAD

**Issue by mklenk1981** [Project-OSRM/node-osrm#79]
I had a script that uses the table function to output a distance table for another application.  This works in version 4.4.0-final, but not in version 4.5.  Did the function call change?
 
---

var OSRM = require('osrm');
osrm = new OSRM(process.argv[2]); 
osrm.table({coordinates: JSON.parse(process.argv[3])}, function(err, table) {                   
console.log(table);                                                                             
 });

**Comment by DennisOSRM** [comment]
works for me:

```JavaScript
var osrm = new OSRM("berlin-latest.osrm");
var options = {
    coordinates: [[52.519930,13.438640], [52.513191,13.415852]]
};
osrm.table(options, function(err, table) {
    console.log(table);
}
```

the above snippet is printing

```JSON
[ [ 0, 2207 ], [ 2175, 0 ] ]
```
