### ISSUE TITLE
Missing handlescope in Engine::Run

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/node-osrm#81]
There is no `v8::HandleScope` inside this function: https://github.com/Project-OSRM/node-osrm/blob/master/src/node_osrm.cpp#L325. This means we may have a very small, but persistent leak of any temporary v8 local objects created there. None are obviously created but its not worth risking a leak.

**Comment by TheMarex** [comment]
@springmeyer is this still an issue?

**Comment by springmeyer** [comment]
No longer an issue, was fixed in https://github.com/Project-OSRM/node-osrm/commit/f4b142778556598d10ac43957f88e2604e1638d5 just forgot to close. Thanks for helping clean up the issue queue @TheMarex.
