### ISSUE TITLE
String escaping broken in v4.6.0 branch

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/node-osrm#83]
That is the geometry response from the ```osrm.route``` test on v4.6.0

```
  route_geometry: 'y~pdcBojfsXuBtD_KzQyEdJ|ElL|u@pb@jPdJn^rLhRjGbNdGnRrEg@xJwRdhE[pIi@jKyHv}AqEl}@m@vJu@nJ{@`HeAtGuDnOeEzLaHzM{BxE{BxHiAjIe@rIJfMbCnLlAhE~BhD`C|AbH`@fEcCtEoC`FeDfCgArFL~PxHdh@tW`n@`b@n\\\\hYhU`Rra@~`@x_An~@hSnPgJd^wFtT}Lte@kp@~mCkRbw@uKvd@cJz`@oC|OdNdCpOzBnZnEzH~@ha@zFbGf@rTaAxEbA`HxBtPpFpa@rO_Cv_B_ZlDaMlB',
```
That is the response from master using OSRM v4.5.0:

```
  route_geometry: 'y~pdcBojfsXuBtD_KzQyEdJ|ElL|u@pb@jPdJn^rLhRjGbNdGnRrEg@xJwRdhE[pIi@jKyHv}AqEl}@m@vJu@nJ{@`HeAtGuDnOeEzLaHzM{BxE{BxHiAjIe@rIJfMbCnLlAhE~BhD`C|AbH`@fEcCtEoC`FeDfCgArFL~PxHdh@tW`n@`b@n\\hYhU`Rra@~`@x_An~@hSnPgJd^wFtT}Lte@kp@~mCkRbw@uKvd@cJz`@oC|OdNdCpOzBnZnEzH~@ha@zFbGf@rTaAxEbA`HxBtPpFpa@rO_Cv_B_ZlDaMlB',
```

There is a subtle difference: instead of two "\\" in the new response there are four (before the ```hYhU``` substring). So this suggests there is some sort of escaping happing somewhere?

The response form osrm-routed is fine btw.

**Comment by DennisOSRM** [comment]
OK, sounds like the string is escaped a second time. Adding a `std::cout` at the right spot shows that it's the `NanNew()` call that does the Escaping.

**Comment by DennisOSRM** [comment]
Found a little bit of background: http://www2.warrensburgr6.org/boundary/encoder/pitfalls.html

**Comment by DennisOSRM** [comment]
It looks like this:

The polyline algorithm produces output may contain backslashes. This output is usually stored in strings in which JavaScript wants to escape anything that's a (potential) control character. So, there's a some inconsistency. The inconvenient thing is that osrm-routed does not double quote the backslashes but it should be. 

Question is, where do we fix this in a consistent way?

- node-osrm appears to do the correct thing
- osrm-routed outputs unquoted polylines
- mapbox/polyline generates unquoted polylines, but only decodes quoted ones correctly
- Everything that calls the API is potentially broken, too.

**Comment by TheMarex** [comment]
@DennisOSRM could not reproduce the incompatibility in polyline:

**Comment by DennisOSRM** [comment]
Yes, this inconsistent behavior is utterly confusing. I'd expect `NanNew()` to do the same thing. Do you know if we can tell NaN to treat string as a value instead of a literal (or vice versa).

**Comment by jfirebaugh** [comment]
I am very skeptical that `NanNew` does any escaping.

**Comment by TheMarex** [comment]
Yep @jfirebaugh is right. The actual escaping is happening in [polyline_encoder.cpp:59](https://github.com/Project-OSRM/osrm-backend/blob/master/algorithms/polyline_compressor.cpp#L59)
This works fine when you use ```osrm-routed``` because the actual JSON serializer in OSRM does not escape the strings again.

**Comment by TheMarex** [comment]
Fix is tracked in https://github.com/Project-OSRM/osrm-backend/pull/1397

**Comment by DennisOSRM** [comment]
> I am very skeptical that NanNew does any escaping.

Well, `NanNew()` (or any function/c'tor it called) does escape each and every backslash in the input string.

> Yep @jfirebaugh is right. The actual escaping is happening in polyline_encoder.cpp:59
This works fine when you use osrm-routed because the actual JSON serializer in OSRM does not escape the strings again.

Good findings on double escaping in polyline encoding and NanNew(). Running point on getting the fix into shape.

**Comment by DennisOSRM** [comment]
We should be good to close here.

cc: @TheMarex
