### ISSUE TITLE
Better API docs

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/node-osrm#99]
We should use one of the usual Javascript library documentation tools to get a full API documentation. The examples are pretty okay, but we can do better than that.

**Comment by jfirebaugh** [comment]
Obligatory plug for our own tool: http://documentationjs.github.io/.

**Comment by jakepruitt** [comment]
If you want a fresh set of eyes to start out the docs, I'd love to help out!

**Comment by TheMarex** [comment]
@jakepruitt that would be awesome. Especially with new API around map matching it is important that we point potential users in the right directions (hah, but seriously https://github.com/mapbox/geojson-tidy is a good pointer to have)

**Comment by TheMarex** [comment]
We aim to be as close as possible to https://github.com/Project-OSRM/osrm-backend/wiki/Server-api the HTTP API. If you notice any consistency problems, just shout out: That is most likely a bug.

**Comment by morganherlocker** [comment]
grabbing @jakepruitt @TheMarex

**Comment by springmeyer** [comment]
Not seeing that this has moved yet. Tagging @mapsam who would be in a great position to knock this out given his recent big push on https://github.com/mapnik/node-mapnik/pull/597.

**Comment by TheMarex** [comment]
Sorry for not closing the ticket. In fact we have documentation now https://github.com/Project-OSRM/node-osrm/blob/develop/API.md

**Comment by springmeyer** [comment]
Awesome, thanks for linking that @TheMarex - A potential next action then (once other work has settled) - would be to formally use documentation.js to provide API docs in the format of http://mapnik.org/node-mapnik/documentation/ (and to allow use to keep them up to data via docstrings in the code). But, good to keep this closed - we'll circle back later.

**Comment by springmeyer** [comment]
> A potential next action then (once other work has settled) - would be to formally use documentation.js to provide API docs in the format of http://mapnik.org/node-mapnik/documentation/

Created ticket for this next action: https://github.com/Project-OSRM/node-osrm/issues/149 /cc @mapsam

**Comment by mapsam** [comment]
Awesome, thanks @springmeyer @TheMarex! Added it to my list once `node-mapnik` docs are complete.
